//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameBlogSite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AboutImage { get; set; }
        public string Details { get; set; }
        public string Saying { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string MyGoals { get; set; }
        public string MyHobbies { get; set; }
        public string Conclusion { get; set; }
    }
}
